---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      # imagePullSecrets:
      #   - name: docker-hub
      containers:
        - name: flask-app
          image: docker.io/akhilputhiry/flask-app:1.2.1
          ports:
            - name: http
              containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
